name: Test on all platforms
on:
  push:
  pull_request:

jobs:

  python-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '2.7', '3.6', '3.10' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: python stdin_parent.py
      - run: python stdin_parent.py crash || true


  ruby-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ruby-version: [ '2.6', "3.1" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: ruby stdin_parent.rb
      - run: ruby stdin_parent.rb crash || true


  python-tests-alpine:
    runs-on: ubuntu-latest
    container: "alpine:latest"
    steps:
      - uses: actions/checkout@v3
      - run: apk add gcc libffi-dev make musl-dev npm py3-pip python3-dev && ln -s /usr/bin/python3 /usr/bin/python
      - run: python stdin_parent.py
      - run: python stdin_parent.py crash || true


  java-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java-version: [ "17" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
      - run: javac StdinParent.java && java StdinParent
      - run: javac StdinParent.java && java StdinParent crash || true

  dotnet-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        dotnet-version: [ "5.0.x" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-dotnet@v2
        with:
          java-version: ${{ matrix.dotnet-version }}
      - run: dotnet run
      - run: dotnet run crash || true
